apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authelia
  namespace: auth
spec:
  interval: 10m
  chart:
    spec:
      chart: authelia
      version: 0.10.49
      sourceRef:
        kind: HelmRepository
        name: authelia
        namespace: flux-system
  values:
    configMap:
      storage:
        local:
          enabled: true
      notifier:
        filesystem:
          enabled: true
      session:
        cookies:
          - subdomain: "auth"
            domain: "sshme.in"
            path: "/"
            default_redirection_url: "https://auth.sshme.in"
            name: "authelia_session"
            same_site: "lax"
            expiration: "1h"
            inactivity: "5m"
            remember_me: "1M"
