apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authelia
  namespace: auth
spec:
  interval: 10m
  chart:
    spec:
      chart: authelia
      version: 0.10.49
      sourceRef:
        kind: HelmRepository
        name: authelia
        namespace: flux-system
  values:
    pod:
      kind: Deployment

    configMap:
      authentication_backend:
        file:
          enabled: true
          path: /config/users_database.yml

        notifier:
          filesystem:
            enabled: true
            filename: /config/notification.txt

        storage:
          local:
            enabled: true
            path: /config/db.sqlite3

        session:
          cookies:
            - domain: "sshme.in"
