apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metallb
spec:
  interval: 10m
  releaseName: metallb
  targetNamespace: metallb-system
  chart:
    spec:
      chart: metallb
      version: 0.15.2
      sourceRef:
        kind: HelmRepository
        name: metallb
        namespace: flux-system
  values:
    speaker:
      frr:
        enabled: false
      excludeInterfaces:
        enabled: false
