apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metallb
spec:
  interval: 10m
  chart:
    spec:
      chart: metallb
      version: 0.15.2
      sourceRef:
        kind: HelmRepository
        name: metallb
        namespace: flux-system
  values:
    speaker:
      frr:
        enabled: false
      excludeInterfaces:
        enabled: false
      interfaces:
        - enp1s0
        - bond0
        - enP3p49s0
        - enP4p65s0
