apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ambeint
spec:
  interval: 10m
  chart:
    spec:
      chart: ambient
      version: 1.28.0
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
