apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: gateway-api
  namespace: flux-system
spec:
  interval: 5m
  prune: true
  sourceRef:
    kind: OCIRepository
    name: flux-system
  path: "./"
  dependsOn: []
  targetNamespace: kube-system
  fetch:
    url: https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.4.0/experimental-install.yaml
