apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ztunnel
spec:
  interval: 10m
  chart:
    spec:
      chart: ztunnel
      version: 1.28.0
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
