apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-flux-internal
  namespace: flux-system
spec:
  podSelector: {}
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: flux-system
  egress:
    - {}
  policyTypes:
    - Ingress
    - Egress
