apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: lldap
spec:
  interval: 10m
  chart:
    spec:
      chart: lldap
      version: 0.10.49
      sourceRef:
        kind: HelmRepository
        name: self-hosters-by-night
        namespace: flux-system
